version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: hydrous_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-hydrous}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hydrous_password}
      POSTGRES_DB: ${POSTGRES_DB:-hydrous_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hydrous"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: hydrous_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@hydrous.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
